version: "3.9"
services:
    postgres-pg:
        container_name: postgres-pg
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: kpis
            POSTGRES_PASSWORD: kpis
        ports:
            - "6500:5432"
        volumes:
            - ./postgres-pg.db.init.sh:/docker-entrypoint-initdb.d/postgres-kpis.db.init.sh
volumes:
    postgres-kpis:
        driver: local
