#!/usr/bin/env python3
#

from argparse                           import ArgumentParser, RawDescriptionHelpFormatter
from bcore.std                          import proj, pro, pre
import json
from datetime                           import datetime, timedelta
from core.db                            import BugsTable


class TableLoader():
    def __init__(self):
        pass

def load(bug):
    m = {
        'id'          : bug['BugId'],
        'module'      : bug['ModuleInfo']['Value'],
        'regression'  : bug['Regression'],
        'ts_opened'   : bug['RequestUtcDate'],
        'ts_closed'   : bug['ClosedDate'],
        'ts_fixed'    : bug['FixedDate'],
        'requester'   : bug['Requester']['Value'] if bug['Requester'] is not None else 'NULL',
        'disposition' : bug['Disposition']['Value'],
        'engineer'    : bug['Engineer']['Value'] if bug['Engineer'] is not None else 'NULL',
        'os'          : bug['OperatingSystems'],
    }
    BugsTable(m['module']).add(m)


if __name__ == '__main__':
    # Command line argument setup and initial processing
    #
    app_description = '''
    '''
    app_epilog = '''
examples:
    listen --help
    '''
    parser = ArgumentParser(description=app_description, epilog=app_epilog, formatter_class=RawDescriptionHelpFormatter)
    parser.add_argument('bugs', nargs="?", help='json formatted file containing all the bugs that match certain search criteria')
    args = parser.parse_args()

    with open(args.bugs, 'r') as f:
        bugs = json.loads(f.read())

    for id in sorted(list(bugs['bugs'].keys())):
        load(bugs['bugs'][id])

# vi:set ts=4 sw=4 expandtab:
